name: my workflow demo 

on: 
  push:
    branches: 
      - master

jobs:
  artifacts_demo_job:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build jar
      run: |
        pwd  && ls -l
        ./gradlew -x jar build
        ls -l build/libs/api-demo-0.0.1-SNAPSHOT.jar
    - name: Archive SNAPSHOT.jar
      uses: actions/upload-artifact@v1
      with:
        name: api_snapshot_jar
        path: build/libs/api-demo-0.0.1-SNAPSHOT.jar