name: my workflow demo 

on: 
  push:
    branches: 
      - master
      
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: My step one
      run: echo "Hello ,Github actions, I'm >>My step one<<"
    - name: My step two
      run: |
        echo "My step one begin..."
        echo "doing..."
        echo "Finished!!!"

  my_second_job:
    name: My second job
    runs-on: macos-latest
    steps:
      - name: check OS info
        run : system_profiler SPSoftwareDataType

  my_third_job:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install ninja-build
      - run: |
          ninja --version
          echo "without step name"
          hostname

  container_job:
    runs-on: ubuntu-latest
    container: 'node:current'
    steps:
      - run: |
          hostname
          node -v