name: my workflow demo 

on: 
  push:
    branches: 
      - master
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: My step one
      run: echo "Hello ,Github actions, I'm >>My step one<<"
    - name: My step one
      run: |
        echo "My step one begin..."
        echo "doing..."
        echo "Finished!!!"
        
