name: pipeline1

on: 
  push:
    branches: 
      - cicd
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout_code
      uses: actions/checkout@v1

    - name: build_jar
      run: ./gradlew -x jar build

    - name: build_image
      run: docker build . --file Dockerfile --tag cicddraft/api-test-demo:$(date "+%Y%m%d%H")

    # - name: Get the version
    #   run: |
    #     echo ${GITHUB_REF:10}
  
  
    # - name: Run a single-line script
    #   run: |
    #     echo "Hello World!"
    #     VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') 
    #     echo $VERSION

    #  - name: push_to_dockerhub
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: cicddraft/api:tagname
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push_image
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 
        docker push cicddraft/api-test-demo:$(date "+%Y%m%d%H")
