name: pipeline1

on: 
  push:
    branches: 
      - cicd
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build_Image
      run: docker build . --file Dockerfile --tag api-test-demo:$(date +%s)

      
